name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  test-backend:
    name: Backend Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "9.x"

      - name: Run Backend Tests
        run: |
          for testProject in $(find src -name "*.Tests.csproj"); do
            echo "Running tests in $testProject"
            dotnet test "$testProject" --collect:"XPlat Code Coverage"
          done

  test-frontend:
    name: Frontend Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Install Dependencies
        run: |
          cd src/FlagExplorerApp.Web
          npm install --legacy-peer-deps

      - name: Run Frontend Tests
        run: |
          cd src/FlagExplorerApp.Web
          npm run test

  build-backend:
    name: Build Backend
    runs-on: ubuntu-latest
    needs: [test-backend]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "9.x"

      - name: Build .NET Backend
        run: |
          cd src
          dotnet publish -c Release -o output

      - name: Upload Backend Artifact
        uses: actions/upload-artifact@v3
        with:
          name: FlagExplorerApp
          path: src/output

  build-frontend:
    name: Build Frontend
    runs-on: ubuntu-latest
    needs: [test-frontend]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Install Dependencies & Build
        run: |
          cd src/FlagExplorerApp.Web
          npm install --legacy-peer-deps
          npm run build

      - name: Upload Frontend Artifact
        uses: actions/upload-artifact@v3
        with:
          name: FlagExplorerApp.Web
          path: src/FlagExplorerApp.Web/dist

  package:
    name: Package for Deployment
    runs-on: ubuntu-latest
    needs: [build-backend, build-frontend]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: List Available Artifacts
        run: ls -R $GITHUB_WORKSPACE

      - name: Download Backend Artifact
        uses: actions/download-artifact@v3
        with:
          name: FlagExplorerApp
          path: src

      - name: Download Frontend Artifact
        uses: actions/download-artifact@v3
        with:
          name: FlagExplorerApp.Web
          path: src/FlagExplorerApp.Web
